#!/bin/bash -e
#
# Copyright 2016, Intel Corporation
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in
#       the documentation and/or other materials provided with the
#       distribution.
#
#     * Neither the name of the copyright holder nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
#
# strace_ebpf_config/TEST0 -- test for strace_ebpf default config and cl arguments
#
export UNITTEST_NAME=strace_ebpf_config/TEST0
export UNITTEST_NUM=0

. ../unittest/unittest.sh

require_test_type medium

require_fs_type any

setup

STRACE_EBPF=./strace_ebpf_config$EXESUFFIX

OUT=stdout${UNITTEST_NUM}.log
LOG=out${UNITTEST_NUM}.log
LOG_TEMP=out${UNITTEST_NUM}_temp.log
rm -rf $OUT $LOG $LOG_TEMP

CONFIG=in${UNITTEST_NUM}.conf
INVALID_CONFIG=$DIR/invalid.conf

expect_normal_exit $STRACE_EBPF 1>> $OUT 2>&1
cat $LOG >> $LOG_TEMP

expect_normal_exit $STRACE_EBPF -V 1>> $OUT 2>&1
cat $LOG >> $LOG_TEMP

expect_normal_exit $STRACE_EBPF --version 1>> $OUT 2>&1
cat $LOG >> $LOG_TEMP

expect_normal_exit $STRACE_EBPF -h 1>> $OUT 2>&1
cat $LOG >> $LOG_TEMP

expect_normal_exit $STRACE_EBPF --help 1>> $OUT 2>&1
cat $LOG >> $LOG_TEMP

expect_normal_exit $STRACE_EBPF -c $CONFIG 1>> $OUT 2>&1
cat $LOG >> $LOG_TEMP

expect_normal_exit $STRACE_EBPF --config $CONFIG 1>> $OUT 2>&1
cat $LOG >> $LOG_TEMP

expect_abnormal_exit $STRACE_EBPF -c $INVALID_CONFIG 1>> $OUT 2>&1
cat $LOG >> $LOG_TEMP

expect_abnormal_exit $STRACE_EBPF --config $INVALID_CONFIG 1>> $OUT 2>&1
cat $LOG >> $LOG_TEMP

grep -v strace_ebpf_config $LOG_TEMP > $LOG

check

pass
